import { assets } from "../../assets/assets"
export const cardData = [
    {
        id: 1,
        imgSrc: assets.bodyBuilder,
        name: "Semeon Panda",
        gender: "Male",
        address: "Los Angeles",
        followers: "7.9M",
        minAdverCost:"1200",
        maxAdverCost: "1500",
    },
    {
        id: 2,
        imgSrc: assets.bodyBuilder,
        name: "Semeon Panda",
        gender: "Male",
        address: "Los Angeles",
        followers: "7.9M",
        minAdverCost:"1200",
        maxAdverCost: "1500",
    },
    {
        id: 3,
        imgSrc: assets.bodyBuilder,
        name: "Semeon Panda",
        gender: "Male",
        address: "Los Angeles",
        followers: "7.9M",
        minAdverCost:"1200",
        maxAdverCost: "1500",
    },
    {
        id: 4,
        imgSrc: assets.bodyBuilder,
        name: "Semeon Panda",
        gender: "Male",
        address: "Los Angeles",
        followers: "7.9M",
        minAdverCost:"1200",
        maxAdverCost: "1500",
    },
    {
        id: 5,
        imgSrc: assets.bodyBuilder,
        name: "Semeon Panda",
        gender: "Male",
        address: "Los Angeles",
        followers: "7.9M",
        minAdverCost:"1200",
        maxAdverCost: "1500",
    },
    {
        id: 6,
        imgSrc: assets.bodyBuilder,
        name: "Semeon Panda",
        gender: "Male",
        address: "Los Angeles",
        followers: "7.9M",
        minAdverCost:"1200",
        maxAdverCost: "1500",
    },
    {
        id: 7,
        imgSrc: assets.bodyBuilder,
        name: "Semeon Panda",
        gender: "Male",
        address: "Los Angeles",
        followers: "7.9M",
        minAdverCost:"1200",
        maxAdverCost: "1500",
    },
    {
        id: 8,
        imgSrc: assets.bodyBuilder,
        name: "Semeon Panda",
        gender: "Male",
        address: "Los Angeles",
        followers: "7.9M",
        minAdverCost:"1200",
        maxAdverCost: "1500",
    },
]